# -*- coding: utf-8 -*-
"""Classification_Task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nuQ2Mndyqy0i4z-O_tXnE43SVIzrs__6

In this part of the project, a Convolutional Neural Network is used to classify natural scene images.  
The dataset used is the Intel Image Classification dataset, which contains six classes: buildings, forest, glacier, mountain, sea, and street.

The objective is to train a CNN model that can recognize the scene category of an input image.
"""

import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import os
import zipfile

from google.colab import drive

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Dense, Flatten, Conv2D, MaxPooling2D, Dropout

drive.mount('/content/drive')

zip_path = '/content/drive/MyDrive/Computer Vision Project/ClassificationDataset.zip'
extract_path = '/content/IntelDataset'

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print(os.listdir(extract_path))

"""Before training the CNN, some sample images are visualized in order to understand the different scene categories contained in the dataset."""

train_path = '/content/IntelDataset/seg_train/seg_train'

classes = os.listdir(train_path)

print('Classes:')
print(classes)

import matplotlib.image as mpimg

plt.figure(figsize=(15,8))

for i, c in enumerate(classes):

    img_name = os.listdir(os.path.join(train_path,c))[0]

    img_path = os.path.join(train_path,c,img_name)

    img = mpimg.imread(img_path)

    plt.subplot(2,3,i+1)
    plt.imshow(img)
    plt.title(c)
    plt.axis('off')

plt.tight_layout()
plt.show()

"""The images are loaded from the class folders using ImageDataGenerator. The pixel values are rescaled from 0-255 to 0-1 and part of the training data is used as validation data."""

train_path = '/content/IntelDataset/seg_train/seg_train'
test_path = '/content/IntelDataset/seg_test/seg_test'

IMG_SIZE = 150
BATCH_SIZE = 64

train_datagen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2,
    horizontal_flip=True,
    zoom_range=0.2
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='training'
)

val_generator = train_datagen.flow_from_directory(
    train_path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    subset='validation'
)

test_generator = test_datagen.flow_from_directory(
    test_path,
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False
)

print(train_generator.class_indices)

"""A CNN model is built using convolution and pooling layers for feature extraction, followed by dense layers for classification. Dropout was also added to reduce overfitting.



"""

model = Sequential()

model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(IMG_SIZE,IMG_SIZE,3)))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(128, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())

model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))

model.add(Dense(6, activation='softmax'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.summary()

"""The model is now trained using the training set while monitoring the validation set performance after each epoch."""

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=15
)

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train','Validation'])

plt.subplot(1,2,2)
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Model loss')
plt.ylabel('Loss')
plt.xlabel('Epoch')
plt.legend(['Train','Validation'])

plt.tight_layout()
plt.show()

score = model.evaluate(test_generator)

print('Test loss = {}'.format(score[0]))
print('Test accuracy = {}'.format(score[1]))

"""The CNN achieved a final training accuracy of approximately 90%, while the validation and test accuracies were around 85%. The close agreement between validation and test performance indicates that the model generalizes well to unseen images. A slight degree of overfitting can be observed after approximately 10 epochs, where the training accuracy continues to increase while the validation accuracy stabilizes."""

from sklearn.metrics import confusion_matrix
import seaborn as sns

y_pred = model.predict(test_generator)

y_pred_classes = np.argmax(y_pred, axis=1)

cm = confusion_matrix(test_generator.classes,
                      y_pred_classes)

plt.figure(figsize=(8,6))

sns.heatmap(cm,
            annot=True,
            fmt='d',
            cmap='Blues',
            xticklabels=list(train_generator.class_indices.keys()),
            yticklabels=list(train_generator.class_indices.keys()))

plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Confusion Matrix')

plt.show()

"""Most classes are classified well. The strongest confusion is between glacier and mountain, which is expected because both contain similar rocky/icy landscape structures. Some streets are also confused with buildings because both contain urban elements."""

from sklearn.metrics import classification_report

class_names = list(test_generator.class_indices.keys())

print(classification_report(test_generator.classes,
                            y_pred_classes,
                            target_names=class_names))

"""The model achieved an overall test accuracy of approximately 85%. The best performing class was forest, with precision and recall values close to 0.93 and 0.99 respectively, indicating that forest scenes are easily distinguishable from the other categories. The most challenging classes were glacier and mountain, which is consistent with the confusion matrix since both classes contain similar landscape characteristics. Buildings and street images also showed some confusion due to the presence of common urban structures. Overall, the model demonstrates good generalization across all six scene categories."""

import random
from tensorflow.keras.preprocessing import image

class_names = list(test_generator.class_indices.keys())

plt.figure(figsize=(15,10))

for i in range(0,9):

    rand_class = random.choice(class_names)

    rand_file = random.choice(
        os.listdir(os.path.join(test_path, rand_class))
    )

    img_path = os.path.join(test_path,
                            rand_class,
                            rand_file)

    img = image.load_img(img_path,
                         target_size=(IMG_SIZE, IMG_SIZE))

    img_array = image.img_to_array(img)

    img_array = img_array / 255.0

    img_input = np.expand_dims(img_array, axis=0)

    prediction = model.predict(img_input, verbose=0)

    predicted_class = class_names[np.argmax(prediction)]

    plt.subplot(3,3,i+1)
    plt.imshow(img_array)
    plt.title('True: {}\nPred: {}'.format(rand_class,
                                          predicted_class))
    plt.axis('off')

plt.tight_layout()
plt.show()

"""Several randomly selected test images are shown here which were classified using the trained CNN. Most scene categories were correctly identified, particularly forest, sea and mountain images, which contain distinctive visual characteristics. Some misclassifications can be observed, especially between mountain and sea scenes, since these categories often share similar colors, textures and landscape structures. Overall, the examples confirm the results obtained from the confusion matrix and demonstrate that the model is capable of generalizing well to previously unseen images."""